set nu rnu
syntax on

colo default

set cursorline
set tabstop=3 shiftwidth=3 expandtab smartindent
set incsearch hlsearch
set virtualedit=all mouse=a
set scrolloff=3

let mapleader=" "

nnoremap <silent> <leader>e :Ex<CR>
nnoremap <silent> <leader>h :tabp<CR>
nnoremap <silent> <leader>l :tabn<CR>
nnoremap <silent> <leader>n :tabnew<CR>
nnoremap <silent> <leader>q :tabclose<CR>
